[Feature/network] 네트워킹 기본 템플릿 구현
Nexters/Naenio-iOS pull request #10
Opened 2022-07-17 17:23 UTC by Choyoonyoung98

## 네트워킹 기본 템플릿 구현
> Moya + RxSwift 기반으로 네트워킹 뼈대 구현했습니다.

- [x] 네트워킹에 필요한 pod 추가
   - `Moya`, `Moya/RxSwift`, `Kingfisher`, `Then`, `RxSwift`, `RxCocoa`
- [x] gitignore 추가
- [x] API endpoint 케이스 정의
- [x] Error Handling 정의
- [x] request 메서드 정의

+) 추가로 진행한 사항
- [x] Github PR / Issue template
-> 목적: PR/Issue 작성에 대한 고민을 줄이고, 간편하게 작성하기 위함
- [ ] SwiftLint (반영 후 Merge 예정.. 셋팅하는 거 까먹고 있었네요)

### 논의사항
1) Github PR/Issue template를 임의로 추가해보았는데 반영해도 괜찮을까요? 사용여부 및 사용한다면 변경하고싶은 내용 말씀해주세요
2) Networking 파일 구분을 원래는 기능별로 나누려고 했었는데,(ex. AuthorizaitonAPI, HomeAPI) 짜다보니 역할 별 구분이 더 명시적일 것 같아서 이렇게 구현해두기는 했습니다만, 기능별 구분이 더 낫다고 생각하시면 말씀해주세욤 반영하겠습니다

#### +) 참고사항
- Error 및 Success에 따른 분기처리는 해두었습니다만, 분기에 따른 행동 정의는 함께 논의해보고 작성하는 게 좋을 것 같아 우선 log 찍히게 구현해두었습니다. 
- `HttpResponseCode.swift` 파일은 분기처리를 더 명시적으로 하는 게 좋을까하는 생각에 우선 만들어두었습니다..

2022-07-18 07:28 UTC, enebin requested changes
조모이님 PR 훑어봤습니다! 너무 잘 만드셔서 제가 드릴 말씀이 많이 없었지만.. 궁금한 것들 몇가지 담아 감히 리뷰 남겨 봤습니다 🙇 

앞으로도 화이팅입니다. 감사해요!!

ps.
- 혹시 리퀘스트는 NaenioAPI.request로 한다고 생각하면 되나요..? Moya를 안 써봐서 구조가 어떻게 되는지 잘 감이 안오네요ㅜㅜ
- 논의사항 관해서
  - 1번은 저는 괜찮아요.
  - 2번의 경우 혹시 Networking 파일 구분이 어떤 걸 말씀하시는 건지 좀 더 자세히 설명 부탁드려도 될까요?

2022-07-18 07:28 UTC, enebin commented on Naenio/Utils/Extension/TargetType+Extension.swift
> +    static func isNotConnection(error: Error) -> Bool {
자잘한 제안사항인데요. `.notConnectedToInternet`에 대한 메소드니까 이름을 `isNotConnected`로 바꾸면 어떨까 한데 어떻게 생각하시나요??

2022-07-18 07:28 UTC, enebin commented on Naenio/Utils/Extension/TargetType+Extension.swift
> +    static func converToURLError(_ error: Error) -> URLError? {
오타인 것 같은데 맞나요?`converToURLError` -> `convertToURLError`

2022-07-18 07:28 UTC, enebin commented on Podfile
> +  pod 'RxCocoa'
저도 SwiftUI에 rx는 처음 넣어봐서 잘 모르지만 검색해보니 RxCocoa는 SwiftUI에서 안 쓰이는 것 같습니다..? 빼셔도 될 것 같아요!

2022-07-18 07:28 UTC, enebin commented on Podfile
> +  pod 'Then'
위 `Then` 코멘트 참조

2022-07-18 07:28 UTC, enebin commented on Naenio/Utils/Network/Common/ModelType.swift
> +import Then
위 `Then` 코멘트 참조

2022-07-18 07:28 UTC, enebin commented on Naenio/Utils/Network/API/NaenioAPI+Wrapper.swift
> +import Then
제가 틀렸을 수도 있는데 `Then`은 SwiftUI에서 못 쓰는 걸로 알고 있습니다..! 혹시 `Then`을 import 하신 이유가 있을까요?

2022-07-19 13:47 UTC, Choyoonyoung98 commented on Naenio/Utils/Extension/TargetType+Extension.swift
> +    static func isNotConnection(error: Error) -> Bool {
넵 반영하겠습니다 👍🏻

2022-07-19 13:47 UTC, Choyoonyoung98 commented on Naenio/Utils/Extension/TargetType+Extension.swift
> +    static func converToURLError(_ error: Error) -> URLError? {
아이고 오타입니다 :( 찾아주셔서 감사합니다

2022-07-19 13:49 UTC, Choyoonyoung98 commented
`Then`, `RxCocoa` 라이브러리는 걷어내겠습니다! 
이것저것 츄라이해보는 과정에서 못걷어내고 코드에 들어간 것 같네요 :(

2022-07-19 14:46 UTC, Choyoonyoung98 commented
### Moya 가이드
> 혹시 리퀘스트는 NaenioAPI.request로 한다고 생각하면 되나요..? Moya를 안 써봐서 구조가 어떻게 되는지 잘 감이 안오네요ㅜㅜ

저도 잘 모르지만,, 아는 선에서 말씀드리자면,,  
1) NaenioAPI에 사용할 API 리스트 enum 추가
```
//NaenioAPI.swift
enum NaenioAPI {
    case login(LoginRequestInformation)
}
```

2. path 추가 (이거 swagger에 나온 api 집어넣었는데, 확정인지 몰라서 확인 후 변경해주세요!)
```
//NaenioAPI+Path
extension NaenioAPI {
    func getPath() -> String {
        switch self {
        case .login: return "/app/login"
        }
    }
}
```

3.  RequestModel(`LoginRequestModel`), ResponseModel 생성
공통 모델 프로토콜 구현해뒀으니, 채택하셔서 사용하시면 될 것 같아요 :)
```
struct LoginRequestInformation: ModelType {
    let accessToken: String
}

struct LoginResponseModel: ModelType {
   let authToken: String
   let authServiceType: String
}
```

4. Moya를 통한 Request

```
let loginRequest = LoginRequestInformation()
NaenioAPI.login(loginRequest)
   .request()
   .map {
      let jsonString = try? $0.mapString().removedEscapeCharacters
      guard let value = jsonString.data(using: .utf8)
      let response  = Response(
         statusCode: $0.statusCode,
         data: value,
         request: $0.request,
         response: $0.response
      )
      
      return response
   }
   .map(LoginResponseModel.self, using: NaenioAPI.jsonDecoder)
   .asObservable()
   .disposed(by: disposeBag)
}
```

+) 엇 근데 적다보니 escape characters(`\`) 제거하는 extension 필요하겠네요. 추가하겠습니다!
+) 그리고 적다보니 [NSObject+Rx](https://github.com/RxSwiftCommunity/NSObject-Rx) 로 disposeBag 처리하는 것도 좋을 것 같네요 :)

### Networking 파일 분리
> 혹시 Networking 파일 구분이 어떤 걸 말씀하시는 건지 좀 더 자세히 설명 부탁드려도 될까요?

- 하고싶은 것: api 증가에 따라 NaenioAPI 파일이 길어져서 복잡해질 것 같아 파일 분리
- 어떻게? 역할별 분리 vs 기능별 분리

1) 역할별 분리(현재 채택)
`getBaseURL()`, `getPath()`, `getMethod()`, `getTask()` 등을 별도의 파일에서 정의
ex. NaenioAPI+Path.swift, Naenio+Task.swift

2) 기능별 분리
- AuthorizationAPI, HomeAPI 등 기능별 파일이 구현됨(역할별 파일 분리 X)
```
enum AuthorizationAPI {
    case socialSignIn(authType: String, accessCode: String)
    case appleSignIn(authorizationCode: String, identityToken: String)
}

extension AuthorizationAPI: TargetType {
    var baseURL: URL {
        return URL(string: KeyValue.baseURL)!
    }
    
    var path: String {
        switch self {
        case .socialSignIn: return "/auth/socialSingnIn"
        case .appleSignIn: return "/auth/appleSignIn"
        }
    }
    
    var method: Moya.Method {
         return .post
    }
  
    var sampleData: Data {
        return Data()
    }
    
    var task: Task {
        switch self {
        case .signOut, .withDrawal:
            return .requestPlain
            
        case .socialSignIn(let authType, let accessCode):
            let parameters: [String: Any] = [
                "authType": authType,
                "accessCode": accessCode
            ]
            return .requestParameters(parameters: parameters, encoding: JSONEncoding.default)
            
        case .appleSignIn(let authorizationCode, let identityToken):
            let parameters: [String: Any] = [
                "authorizationCode": authorizationCode,
                "identityToken": identityToken
            ]
            return .requestParameters(parameters: parameters, encoding: JSONEncoding.default)
       }
    }

    var headers: [String: String]? {
        switch self {
        case .appleSignIn, .socialSignIn:
            return [HeaderInformation.HeaderKey.contentType: HeaderInformation.HeaderValue.json]
        default:
            return [
                HeaderInformation.HeaderKey.contentType: HeaderInformation.HeaderValue.json,
                HeaderInformation.HeaderValue.authoization: HeaderInformation.HeaderValue.authoization
            ]
        }
    }
}

```

2022-07-19 15:00 UTC, enebin commented
파일 분리는 1번 방식으로 하는 게 좋을 것 같습니다. 2번 방식으로 하면,, 끝도 없이 코드가 늘어날 것 같아요. 추가적으로 작업하셔야 되는 것도 있구요.

2022-07-20 11:53 UTC, merged