[Networking] 대댓글 조회 API 연결 및 대댓글 작성 APi 확인 완료
Nexters/Naenio-iOS pull request #83
Opened 2022-08-23 15:27 UTC by Choyoonyoung98

## 개요
대댓글 조회 API 연결 및 기타사항 수정
> /app/comments/{id}/comment-replies

```
endpoint: Wrapper(base: Naenio.NaenioAPI.getCommentReplies(postId: 244, model: Naenio.CommentRepliesRequestModel(size: 10, lastCommentId: nil)))
REQUEST: HTTPMethod(rawValue: "GET") https://teamversus.shop /app/comments/244/comment-replies /Users/cho-yoonyoung/Naenio-iOS-dev/Naenio/Utils/Network/Service/RequestService.swift request(api:) 11
🛰 SUCCESS: HTTPMethod(rawValue: "GET") https://teamversus.shop /app/comments/244/comment-replies (200) /Users/cho-yoonyoung/Naenio-iOS-dev/Naenio/Utils/Network/Service/RequestService.swift request(api:) 11
Success requestComments
Disposed requestComments
```

## 작업 내용
- [x] 대댓글 조회 API 연결
- [x] 대댓글 생성 APi 확인 
- [x] 탭뷰 화면 상단에 navigation bar 공간 생김 현상 수정
- [x] 기타 버그 수정

## 참고 사항
말씀해주신 내용 참고하여 대댓글이 독립적인 viewModel을 가질 수 있도록 수정했습니다.

// TODO: 댓글 및 대댓글 작성 시, 리스트 자동 갱신되도록 수정 필요

2022-08-25 01:05 UTC, enebin requested changes

2022-08-25 01:05 UTC, enebin commented on Naenio/Sources/Home/Comment/CommentRepliesViewModel.swift
> +    func transferToCommentModel(from comment: CommentPostResponseModel) -> Comment {
이 부분이 모든 뷰모델마다 반복되는 것 같은데 이 기능해 해당하는 메소드를 `OOOResponseModel`의 extension으로 빼면 어떨까 싶습니다.  그러면 viewModel이 조금 깔끔해질 것 같아서요. `toDictionary`만드셨던 것 처럼요! 다른 거 다 바꿀 필요는 없고 일단 여기부터 해놓고 다른 데는 눈에 띌 때 수정하면 좋을 것 같습니다.

선택사항입니다.  시간이 걸리겠다 싶으면 `private`처리만 해주십셔.

➕ 이건 다른 얘긴데 Post, Author 이런 거 전체적으로 통일 좀 시켜야될 것 같습니다. 어디는 그냥 Post고 어디는 FeedResponse의 post고 그래가지고...

2022-08-25 01:05 UTC, enebin commented on Naenio/Sources/Home/Comment/CommentView.swift
> +            viewModel.requestComments(postId: self.parentId, isFirstRequest: true)
이건 전에 봤을 때 그냥 궁금한 거였는데 `isFirstRequest`를 받는 이유가 있나요??

2022-08-26 00:41 UTC, enebin commented
뒤 작업들 땜에 머지 먼저 할게요~ 리뷰도 그냥 알아만 두십셔. 필요한 건 제가 고칠게요ㅎ

2022-08-26 00:42 UTC, merged

2022-08-28 08:43 UTC, Choyoonyoung98 commented on Naenio/Sources/Home/Comment/CommentView.swift
> +            viewModel.requestComments(postId: self.parentId, isFirstRequest: true)
리스트에 대해 처음 받아오거나, 새로고침할 경우 `isFirstRequest:true`를 받아오고 있습니다.
받는 이유는, 해당 조건 상황에 대해서 comments 리스트를 비워주고 초기화해주기 위함입니다.

무한스크롤을 위해, 추가 스크롤 행위가 발생 할 경우 `isFirstRequest: false`로 호출한 다음, 
comments 리스트에 api를 통해 불러온 데이터들을 add해주는 방식으로 구현했습니다.

```
if isFirstRequest {
   self.comments = commentInfo.comments
} else {
   self.comments.append(contentsOf: commentInfo.comments)
}
```
이렇게 되면 기존의 **requestMoreComment()** 등과 같은 함수를 추가 구현할 필요 없이 하나의 함수로 해결할 수 있습니다.

2022-08-28 08:46 UTC, Choyoonyoung98 commented
splash는 
- gradient asset파일이 device에서 인식되지 않을 때가 있어서,, 
- spash화면도 코드로 뷰를 작업할 수 있는 방법이 있는지 찾아보고싶어서

새로 작업하고 새 PR로 올리겠습니다.